# Generated by Django 5.2 on 2025-06-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relotagrid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetardJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.TimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relotagrid.agent')),
            ],
            options={
                'unique_together': {('agent', 'date')},
            },
        ),
    ]
