# Generated by Django 5.2 on 2025-05-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relotagrid', '0004_alter_agent_options_alter_critere_options_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='livraisonmensuelle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='livraisonmensuelle',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_stock', to='relotagrid.site'),
        ),
        migrations.AlterUniqueTogether(
            name='livraisonmensuelle',
            unique_together={('site', 'produit', 'mois')},
        ),
    ]
