# Generated by Django 5.2 on 2025-05-06 07:41

import django.core.validators
import django.db.models.deletion
import relotagrid.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_local', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ElementControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('critere', models.ManyToManyField(to='relotagrid.critere')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_controle', models.ManyToManyField(to='relotagrid.elementcontrol')),
                ('local_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relotagrid.localtype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relotagrid.site')),
            ],
        ),
        migrations.CreateModel(
            name='GrilleControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relotagrid.local')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=9, validators=[relotagrid.validators.validate_numero_congo, django.core.validators.MinLengthValidator(9)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='agents/images/', verbose_name="Image de l'agent")),
                ('cv', models.FileField(blank=True, null=True, upload_to='agents/cv/', verbose_name="CV de l'agent")),
                ('site', models.ManyToManyField(to='relotagrid.site')),
            ],
        ),
    ]
