# Generated by Django 5.2 on 2025-06-11 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='agents/images/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='agents/cv/')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critere', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '3. Creer des criteres',
            },
        ),
        migrations.CreateModel(
            name='LocalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_local', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '2. Creer des types de locaux',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': '1. Creer un site',
            },
        ),
        migrations.CreateModel(
            name='ElementControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('critere', models.ManyToManyField(to='relotagrid.critere')),
            ],
            options={
                'verbose_name_plural': '4. Creer des elements de controle',
            },
        ),
        migrations.CreateModel(
            name='GrilleControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlGrille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relotagrid.agent')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relotagrid.critere')),
                ('element_controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relotagrid.elementcontrol')),
                ('grille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='relotagrid.grillecontrol')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_controle', models.ManyToManyField(to='relotagrid.elementcontrol')),
                ('local_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relotagrid.localtype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relotagrid.site')),
            ],
            options={
                'verbose_name_plural': '6. Creation des Locals',
            },
        ),
        migrations.AddField(
            model_name='grillecontrol',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relotagrid.local'),
        ),
        migrations.AddField(
            model_name='agent',
            name='site',
            field=models.ManyToManyField(related_name='agents', to='relotagrid.site'),
        ),
    ]
