# Generated by Django 5.2 on 2025-06-28 13:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relotagrid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
