# Generated by Django 5.2 on 2025-05-12 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relotagrid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlGrille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relotagrid.agent')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relotagrid.critere')),
                ('element_controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relotagrid.elementcontrol')),
                ('grille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relotagrid.grillecontrol')),
            ],
        ),
    ]
