# Generated by Django 5.2 on 2025-05-12 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relotagrid', '0002_controlgrille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlgrille',
            name='grille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='relotagrid.grillecontrol'),
        ),
    ]
