# Generated by Django 5.2 on 2025-06-28 13:51

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relotagrid', '0002_alter_agent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='agents/cv/'),
        ),
    ]
