# Generated by Django 5.2 on 2025-05-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relotagrid', '0003_alter_controlgrille_grille'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name_plural': '5. Creation des agents'},
        ),
        migrations.AlterModelOptions(
            name='critere',
            options={'verbose_name_plural': '3. Creer des criteres'},
        ),
        migrations.AlterModelOptions(
            name='elementcontrol',
            options={'verbose_name_plural': '4. Creer des elements de controle'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name_plural': '6. Creation des Locals'},
        ),
        migrations.AlterModelOptions(
            name='localtype',
            options={'verbose_name_plural': '2. Creer des types de locaux'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name_plural': '1. Creer un site'},
        ),
    ]
