# Generated by Django 5.2 on 2025-06-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relotagrid', '0004_alter_agent_options_alter_critere_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse de l'agent"),
        ),
    ]
