# Generated by Django 5.2 on 2025-06-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relotagrid', '0005_agent_adresse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.AddField(
            model_name='agent',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='agents/cv/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agents/images/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='site',
            field=models.ManyToManyField(related_name='agents', to='relotagrid.site'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
