# Generated by Django 5.2 on 2025-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controleur',
            name='username',
        ),
        migrations.AddField(
            model_name='controleur',
            name='phone_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
