# Generated by Django 5.2 on 2025-06-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('relotagrid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleur',
            name='sites_autorises',
            field=models.ManyToManyField(blank=True, related_name='controleurs_autorises', to='relotagrid.site'),
        ),
        migrations.AddField(
            model_name='controleur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
