# Generated by Django 5.2 on 2025-04-28 12:31

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_controleur_username_controleur_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='controleur',
            managers=[
                ('objects', accounts.models.ControleurManager()),
            ],
        ),
    ]
