# Generated by Django 5.2 on 2025-05-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_controleur_managers'),
        ('relotagrid', '0004_alter_agent_options_alter_critere_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('controleur', 'Contrôleur'), ('sous_controleur', 'Sous-contrôleur')], default='sous_controleur', max_length=20),
        ),
        migrations.AddField(
            model_name='controleur',
            name='sites_autorises',
            field=models.ManyToManyField(blank=True, related_name='controleurs_autorises', to='relotagrid.site'),
        ),
    ]
